version: '3.8'

services:
  
  nginx:
    image: nginx
    ports:
      - 80:80
    volumes:
      - ./src:/usr/share/nginx/html/
      - ./nginx/conf.d:/etc/nginx/conf.d
    depends_on:
      - php-fpm
  
  php-fpm:
    image: php:8.2-fpm
    volumes:
      - ./src:/usr/share/nginx/html

